---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-v2
    spec:
      containers:
      - name: frontend-v2
        image: zzonsang2/spring-boot-k8s-hpa-actuator:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ACTIVEMQ_BROKER_URL
          value: "tcp://queue:61616"
        - name: STORE_ENABLED
          value: "true"
        - name: WORKER_ENABLED
          value: "false"
        - name: QUEUE_NAME
          value: tibco_topic_2_total
        ports:
          - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-v2
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend-v2
  type: NodePort
